language: elixir
elixir:
  - 1.5.2
addons:
  postgresql: '9.5'
services:
  - postgresql
env:
  - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
before_script:
  - cp config/travis.exs config/test.exs
  - mix do deps.get, ecto.create, ecto.migrate
script:
  - mix test